# Generated by Django 2.0 on 2018-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180118_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('sloc', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images')),
                ('resume', models.FileField(upload_to='files')),
            ],
        ),
    ]
