# Generated by Django 2.1.3 on 2018-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(blank=True, max_length=20)),
                ('Ddepartment', models.CharField(blank=True, max_length=20)),
                ('Dhospital', models.CharField(blank=True, max_length=20)),
                ('Demail', models.EmailField(blank=True, max_length=254)),
                ('Dage', models.IntegerField()),
                ('Dfee', models.IntegerField()),
                ('Dprofile', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
