# Generated by Django 2.1.3 on 2018-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_doctor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
            ],
        ),
    ]
