# Generated by Django 2.1.3 on 2018-12-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20181220_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Dage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Dfee',
            field=models.IntegerField(null=True),
        ),
    ]
