# Generated by Django 2.1.3 on 2018-12-20 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20181220_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buldings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=10)),
                ('lname', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcolor', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20)),
                ('lname', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
                ('pub', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Person'),
        ),
        migrations.AddField(
            model_name='buldings',
            name='construction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Construction'),
        ),
    ]
