# Generated by Django 2.1.3 on 2018-12-20 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20181220_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Publisher')),
            ],
            bases=('schedule.publisher',),
            managers=[
                ('pub', django.db.models.manager.Manager()),
            ],
        ),
    ]
