# Generated by Django 2.1.3 on 2018-12-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buldings',
            new_name='Buildings',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='lcolor',
            new_name='icolor',
        ),
    ]
