# Generated by Django 2.1.3 on 2018-12-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20181220_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
