# Generated by Django 2.1.3 on 2018-12-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20181220_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='person',
            new_name='per',
        ),
    ]
