# Generated by Django 2.1.3 on 2018-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20181220_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sloc',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sno',
        ),
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
